import { existsSync, readdirSync, readFileSync, rmSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'

import { writeTextAtomic } from './io.js'

/**
 * The generated function index: one page per `src/` module that states each
 * export's signature, behavior, and location, a module map, and a symbol
 * lookup. A worker reads the entry instead of the function body, and opens
 * source only for the lines it changes.
 */
export const FUNCTION_INDEX_DIRECTORY = 'docs/function-index'

/** Pages longer than this split into numbered parts. */
const MAX_PAGE_LINES = 900

/** A signature longer than this is cut, so one type does not flood a page. */
const MAX_SIGNATURE_CHARS = 600

/** Interfaces list at most this many members; the rest are counted. */
const MAX_MEMBERS = 40

const GENERATED_NOTICE =
  '<!-- Generated by `pan docs index --write`. Do not edit by hand. -->'

type TypeScriptModule = typeof import('typescript')
type Node = import('typescript').Node
type SourceFile = import('typescript').SourceFile

export type IndexEntryKind =
  | 'function'
  | 'const'
  | 'class'
  | 'interface'
  | 'type'
  | 'enum'

export interface IndexEntry {
  name: string
  kind: IndexEntryKind
  line: number
  /** Declaration text without its body, whitespace-collapsed. */
  signature: string
  /** First paragraph of the leading JSDoc, or null when there is none. */
  behavior: string | null
  deprecated: boolean
}

export interface IndexModule {
  /** Repository-relative source path, such as `src/lib/engine.ts`. */
  file: string
  /** First sentence of the file comment, else of the first documented export. */
  summary: string | null
  entries: IndexEntry[]
  /** Modules this one only re-exports from, when it is a facade. */
  reexports: string[]
}

export interface FunctionIndexCheck {
  status: 'current' | 'stale' | 'unavailable'
  stale: string[]
  missing: string[]
  extra: string[]
  message: string
}

let typescriptModule: TypeScriptModule | null | undefined

/**
 * Load the `typescript` devDependency synchronously, so repository
 * validation can run the drift check. Returns null when it is absent.
 */
function loadTypeScriptSync(root: string): TypeScriptModule | null {
  if (typescriptModule !== undefined) {
    return typescriptModule
  }

  for (const base of [path.join(root, 'package.json'), import.meta.url]) {
    try {
      typescriptModule = createRequire(base)('typescript') as TypeScriptModule

      return typescriptModule
    } catch {
      // Try the next base.
    }
  }

  typescriptModule = null

  return typescriptModule
}

function sourceFiles(root: string): string[] {
  const directory = path.join(root, 'src')

  if (!existsSync(directory)) {
    return []
  }

  return readdirSync(directory, { recursive: true, withFileTypes: true })
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name.endsWith('.ts') &&
        !entry.name.endsWith('.d.ts'),
    )
    .map((entry) =>
      path
        .relative(root, path.join(entry.parentPath, entry.name))
        .split(path.sep)
        .join('/'),
    )
    .sort()
}

function collapse(text: string): string {
  return text.replace(/\s+/gu, ' ').trim()
}

function truncate(text: string, limit: number): string {
  return text.length <= limit ? text : `${text.slice(0, limit - 1)}…`
}

/** Strip the comment markers of a JSDoc block into plain paragraphs. */
function jsDocText(block: string): string {
  return block
    .replace(/^\/\*\*/u, '')
    .replace(/\*\/$/u, '')
    .split('\n')
    .map((line) => line.replace(/^\s*\* ?/u, ''))
    .join('\n')
    .trim()
}

function leadingJsDoc(
  ts: TypeScriptModule,
  sourceFile: SourceFile,
  node: Node,
): string | null {
  const ranges =
    ts.getLeadingCommentRanges(sourceFile.text, node.getFullStart()) ?? []
  const block = [...ranges]
    .reverse()
    .find((range) => sourceFile.text.startsWith('/**', range.pos))

  return block ? jsDocText(sourceFile.text.slice(block.pos, block.end)) : null
}

/** The first paragraph of a JSDoc text, without tag lines. */
function firstParagraph(text: string | null): string | null {
  if (!text) {
    return null
  }

  const paragraph = text
    .split(/\n\s*\n/u)[0]
    ?.split('\n')
    .filter((line) => !line.trim().startsWith('@'))
    .join(' ')

  const collapsed = paragraph ? collapse(paragraph) : ''

  return collapsed.length > 0 ? collapsed : null
}

function firstSentence(text: string | null): string | null {
  if (!text) {
    return null
  }

  const match = /^(.+?[.!?])(?:\s|$)/u.exec(text)

  return match?.[1] ?? text
}

function hasExportModifier(ts: TypeScriptModule, node: Node): boolean {
  return (
    ts
      .getModifiers(node as import('typescript').HasModifiers)
      ?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) ===
    true
  )
}

/** Declaration text up to its body, so the entry never carries code. */
function headerText(sourceFile: SourceFile, node: Node, body?: Node): string {
  const start = node.getStart(sourceFile)
  const end = body ? body.getStart(sourceFile) : node.getEnd()

  return collapse(sourceFile.text.slice(start, end))
    .replace(/^export\s+(default\s+)?/u, '')
    .replace(/\s*[{=]\s*$/u, '')
}

function interfaceSignature(
  ts: TypeScriptModule,
  sourceFile: SourceFile,
  node: import('typescript').InterfaceDeclaration,
): string {
  const heading = collapse(
    sourceFile.text.slice(
      node.getStart(sourceFile),
      node.members.pos > node.getStart(sourceFile)
        ? node.members.pos
        : node.getEnd(),
    ),
  )
    .replace(/^export\s+/u, '')
    .replace(/\s*\{\s*$/u, '')
  const members = node.members.slice(0, MAX_MEMBERS).map((member) => {
    const text = collapse(member.getText(sourceFile)).replace(/[;,]$/u, '')
    const doc = firstParagraph(leadingJsDoc(ts, sourceFile, member))

    return `  ${truncate(text, 160)}${doc ? ` // ${truncate(doc, 120)}` : ''}`
  })
  const omitted = node.members.length - members.length

  return [
    `${heading} {`,
    ...members,
    ...(omitted > 0 ? [`  // … ${omitted} more members`] : []),
    '}',
  ].join('\n')
}

function moduleEntries(
  ts: TypeScriptModule,
  sourceFile: SourceFile,
): { entries: IndexEntry[]; reexports: string[] } {
  const entries: IndexEntry[] = []
  const reexports: string[] = []
  const add = (
    name: string,
    kind: IndexEntryKind,
    node: Node,
    docNode: Node,
    signature: string,
  ): void => {
    const doc = leadingJsDoc(ts, sourceFile, docNode)

    entries.push({
      name,
      kind,
      line:
        sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile))
          .line + 1,
      signature:
        kind === 'interface'
          ? signature
          : truncate(signature, MAX_SIGNATURE_CHARS),
      behavior: firstParagraph(doc),
      deprecated: doc?.includes('@deprecated') === true,
    })
  }

  for (const statement of sourceFile.statements) {
    if (
      ts.isExportDeclaration(statement) &&
      statement.moduleSpecifier &&
      ts.isStringLiteral(statement.moduleSpecifier)
    ) {
      reexports.push(statement.moduleSpecifier.text)
      continue
    }

    if (!hasExportModifier(ts, statement)) {
      continue
    }

    if (ts.isFunctionDeclaration(statement) && statement.name) {
      add(
        statement.name.text,
        'function',
        statement,
        statement,
        headerText(sourceFile, statement, statement.body),
      )
    } else if (ts.isClassDeclaration(statement) && statement.name) {
      const members = statement.members
        .filter(
          (member) =>
            (ts.isMethodDeclaration(member) ||
              ts.isConstructorDeclaration(member)) &&
            !ts
              .getModifiers(member)
              ?.some(
                (modifier) =>
                  modifier.kind === ts.SyntaxKind.PrivateKeyword ||
                  modifier.kind === ts.SyntaxKind.ProtectedKeyword,
              ),
        )
        .map(
          (member) =>
            `  ${truncate(headerText(sourceFile, member, (member as import('typescript').MethodDeclaration).body), 200)}`,
        )

      add(
        statement.name.text,
        'class',
        statement,
        statement,
        [
          `${headerText(sourceFile, statement, statement.members[0] ?? undefined)} {`,
          ...members,
          '}',
        ].join('\n'),
      )
    } else if (ts.isInterfaceDeclaration(statement)) {
      add(
        statement.name.text,
        'interface',
        statement,
        statement,
        interfaceSignature(ts, sourceFile, statement),
      )
    } else if (ts.isTypeAliasDeclaration(statement)) {
      add(
        statement.name.text,
        'type',
        statement,
        statement,
        collapse(statement.getText(sourceFile)).replace(/^export\s+/u, ''),
      )
    } else if (ts.isEnumDeclaration(statement)) {
      add(
        statement.name.text,
        'enum',
        statement,
        statement,
        collapse(statement.getText(sourceFile)).replace(/^export\s+/u, ''),
      )
    } else if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        if (!ts.isIdentifier(declaration.name)) {
          continue
        }

        const initializer = declaration.initializer
        const isFunction =
          initializer !== undefined &&
          (ts.isArrowFunction(initializer) ||
            ts.isFunctionExpression(initializer))
        const signature = isFunction
          ? `${declaration.name.text} = ${headerText(sourceFile, initializer, (initializer as import('typescript').ArrowFunction).body)}`
          : declaration.type
            ? `${declaration.name.text}: ${collapse(declaration.type.getText(sourceFile))}`
            : collapse(declaration.getText(sourceFile))

        add(
          declaration.name.text,
          isFunction ? 'function' : 'const',
          declaration,
          statement,
          signature,
        )
      }
    }
  }

  return { entries, reexports }
}

function fileSummary(
  ts: TypeScriptModule,
  sourceFile: SourceFile,
  entries: IndexEntry[],
): string | null {
  const first = sourceFile.statements[0]
  // A file comment sits before the first statement and is separated from
  // it, so it is the first leading block when more than one exists or when
  // the first statement is an import.
  const ranges = first
    ? (ts.getLeadingCommentRanges(sourceFile.text, first.getFullStart()) ?? [])
    : []
  const fileBlock =
    first &&
    (ranges.length > 1 ||
      ts.isImportDeclaration(first) ||
      ts.isExportDeclaration(first))
      ? ranges.find((range) => sourceFile.text.startsWith('/**', range.pos))
      : undefined

  if (fileBlock) {
    return firstSentence(
      firstParagraph(
        jsDocText(sourceFile.text.slice(fileBlock.pos, fileBlock.end)),
      ),
    )
  }

  // Without a file comment the module map names what the module exports,
  // rather than borrowing one export's description for the whole file.
  const functions = entries
    .filter((entry) => entry.kind === 'function')
    .slice(0, 4)
    .map((entry) => `\`${entry.name}\``)

  return functions.length > 0 ? `Exports ${functions.join(', ')}.` : null
}

/** Parse every `src/` module into its index entries. */
export function buildFunctionIndex(root: string): IndexModule[] | null {
  const ts = loadTypeScriptSync(root)

  if (!ts) {
    return null
  }

  return sourceFiles(root).map((file) => {
    const sourceFile = ts.createSourceFile(
      file,
      readFileSync(path.join(root, file), 'utf8'),
      ts.ScriptTarget.Latest,
      true,
    )
    const { entries, reexports } = moduleEntries(ts, sourceFile)

    return {
      file,
      summary: fileSummary(ts, sourceFile, entries),
      entries,
      reexports,
    }
  })
}

function pagePath(file: string, part = 1): string {
  const base = file.replace(/\.ts$/u, '')

  return `${FUNCTION_INDEX_DIRECTORY}/${base}${part > 1 ? `.part-${part}` : ''}.md`
}

function anchor(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9_-]/gu, '')
}

function entryLines(module: IndexModule, entry: IndexEntry): string[] {
  return [
    `### ${entry.name}`,
    '',
    `\`${entry.kind}\` · [\`${module.file}:${entry.line}\`](../../${'../'.repeat(module.file.split('/').length - 1)}${module.file}#L${entry.line})${entry.deprecated ? ' · deprecated' : ''}`,
    '',
    '```ts',
    entry.signature,
    '```',
    '',
    entry.behavior ?? '_Undocumented: read the signature, then the source._',
    '',
  ]
}

/** Split a page body into parts that stay under the page limit. */
function paginate(header: string[], blocks: string[][]): string[][] {
  const pages: string[][] = []
  let current = [...header]

  // A block element can hold a multi-line signature, so lines are counted
  // from the joined text rather than from the element count.
  const lines = (items: string[]): number => items.join('\n').split('\n').length
  let used = lines(current)

  for (const block of blocks) {
    const size = lines(block)

    if (used + size > MAX_PAGE_LINES && current.length > header.length) {
      pages.push(current)
      current = [...header]
      used = lines(current)
    }

    current.push(...block)
    used += size
  }

  pages.push(current)

  return pages
}

function modulePages(module: IndexModule): Map<string, string> {
  const title = `# \`${module.file}\``
  const summary = module.summary ?? '_No module summary._'
  const facade =
    module.reexports.length > 0 && module.entries.length === 0
      ? [
          `Facade: this module only re-exports. Read the page of the module that owns a symbol:`,
          '',
          ...module.reexports.map((specifier) => `- \`${specifier}\``),
          '',
        ]
      : []
  const header = [GENERATED_NOTICE, '', title, '', summary, '', ...facade]
  const order: IndexEntryKind[] = [
    'function',
    'class',
    'const',
    'interface',
    'type',
    'enum',
  ]
  const blocks = order.flatMap((kind) =>
    module.entries
      .filter((entry) => entry.kind === kind)
      .sort((left, right) => left.line - right.line)
      .map((entry) => entryLines(module, entry)),
  )
  const pages = paginate(header, blocks)
  const result = new Map<string, string>()

  pages.forEach((lines, index) => {
    const part = index + 1
    const navigation =
      pages.length > 1
        ? [
            `Part ${part} of ${pages.length}.` +
              (part < pages.length
                ? ` Next: [part ${part + 1}](${path.basename(pagePath(module.file, part + 1))}).`
                : ''),
            '',
          ]
        : []

    result.set(
      pagePath(module.file, part),
      `${[...lines.slice(0, header.length), ...navigation, ...lines.slice(header.length)].join('\n').trimEnd()}\n`,
    )
  })

  return result
}

function readmePages(modules: IndexModule[]): Map<string, string> {
  const intro = [
    GENERATED_NOTICE,
    '',
    '# Function index',
    '',
    'Every exported symbol under `src/`, with its signature, what it does, and where it lives.',
    '',
    '- Find the module for a task in the map below, then open its page.',
    '- Look up a symbol by name in [SYMBOLS.md](SYMBOLS.md).',
    '- A page entry states the interface and behavior. Open the source only for the lines you change.',
    '- The harness regenerates this index whenever it prepares a stage. Outside a run, regenerate it with `./bin/pan docs index --write`.',
    '',
    '## Module map',
    '',
  ]
  const rows = modules.map((module) => {
    const exports = module.entries.length
    const note =
      module.reexports.length > 0 && exports === 0 ? 'facade' : String(exports)

    return [
      `- [\`${module.file}\`](${pagePath(module.file).slice(FUNCTION_INDEX_DIRECTORY.length + 1)}) · ${note} · ${module.summary ?? '—'}`,
    ]
  })
  const pages = paginate(intro, rows)
  const result = new Map<string, string>()

  pages.forEach((lines, index) => {
    const name = index === 0 ? 'README.md' : `README.part-${index + 1}.md`
    const next =
      index + 1 < pages.length
        ? [
            '',
            `Continued in [README.part-${index + 2}.md](README.part-${index + 2}.md).`,
          ]
        : []

    result.set(
      `${FUNCTION_INDEX_DIRECTORY}/${name}`,
      `${[...lines, ...next].join('\n').trimEnd()}\n`,
    )
  })

  return result
}

function symbolPages(modules: IndexModule[]): Map<string, string> {
  const entries = modules
    .flatMap((module) => module.entries.map((entry) => ({ module, entry })))
    .sort(
      (left, right) =>
        left.entry.name.localeCompare(right.entry.name) ||
        left.module.file.localeCompare(right.module.file),
    )
  const header = [
    GENERATED_NOTICE,
    '',
    '# Symbols',
    '',
    'Every exported symbol under `src/`, by name.',
    '',
  ]
  const rows = entries.map(({ module, entry }) => [
    `- \`${entry.name}\` · ${entry.kind} · [\`${module.file}\`](${pagePath(module.file).slice(FUNCTION_INDEX_DIRECTORY.length + 1)}#${anchor(entry.name)})`,
  ])
  const pages = paginate(header, rows)
  const result = new Map<string, string>()

  pages.forEach((lines, index) => {
    const name = index === 0 ? 'SYMBOLS.md' : `SYMBOLS.part-${index + 1}.md`
    const next =
      index + 1 < pages.length
        ? [
            '',
            `Continued in [SYMBOLS.part-${index + 2}.md](SYMBOLS.part-${index + 2}.md).`,
          ]
        : []

    result.set(
      `${FUNCTION_INDEX_DIRECTORY}/${name}`,
      `${[...lines, ...next].join('\n').trimEnd()}\n`,
    )
  })

  return result
}

/** Render the whole index as path → content, or null without TypeScript. */
export function renderFunctionIndex(root: string): Map<string, string> | null {
  const modules = buildFunctionIndex(root)

  if (!modules) {
    return null
  }

  return new Map(
    [
      ...readmePages(modules),
      ...symbolPages(modules),
      ...modules.flatMap((module) => [...modulePages(module)]),
    ].sort(([left], [right]) => left.localeCompare(right)),
  )
}

function indexedFiles(root: string): string[] {
  const directory = path.join(root, FUNCTION_INDEX_DIRECTORY)

  if (!existsSync(directory)) {
    return []
  }

  return readdirSync(directory, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
    .map((entry) =>
      path
        .relative(root, path.join(entry.parentPath, entry.name))
        .split(path.sep)
        .join('/'),
    )
    .sort()
}

/** Compare the index on disk with a fresh render. */
export function checkFunctionIndex(root: string): FunctionIndexCheck {
  const rendered = renderFunctionIndex(root)

  if (!rendered) {
    return {
      status: 'unavailable',
      stale: [],
      missing: [],
      extra: [],
      message:
        'function index not checked: the typescript devDependency is not installed',
    }
  }

  const onDisk = new Set(indexedFiles(root))
  const stale: string[] = []
  const missing: string[] = []

  for (const [relative, content] of rendered) {
    if (!onDisk.has(relative)) {
      missing.push(relative)
    } else if (readFileSync(path.join(root, relative), 'utf8') !== content) {
      stale.push(relative)
    }
  }

  const extra = [...onDisk].filter((relative) => !rendered.has(relative))
  const current = stale.length + missing.length + extra.length === 0

  return {
    status: current ? 'current' : 'stale',
    stale,
    missing,
    extra,
    message: current
      ? 'function index is current'
      : `function index is stale: ${stale.length} changed, ${missing.length} missing, ${extra.length} extra page(s); run ./bin/pan docs index --write`,
  }
}

/** Write the index and remove pages of modules that no longer exist. */
export function writeFunctionIndex(root: string): FunctionIndexCheck {
  const rendered = renderFunctionIndex(root)

  if (!rendered) {
    return checkFunctionIndex(root)
  }

  for (const relative of indexedFiles(root)) {
    if (!rendered.has(relative)) {
      rmSync(path.join(root, relative))
    }
  }

  for (const [relative, content] of rendered) {
    const absolute = path.join(root, relative)

    if (!existsSync(absolute) || readFileSync(absolute, 'utf8') !== content) {
      writeTextAtomic(absolute, content)
    }
  }

  return checkFunctionIndex(root)
}
